<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="8" failures="0" skipped="0" tests="8" time="0.126" timestamp="2024-04-11T00:41:12.078480" hostname="WIN-EL7Q5TVUKSP"><testcase classname="" name="basic_test" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\kskos\PycharmProjects\pythonSeleniumChatGPT\unitTests\basic_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
basic_test.py:1: in &lt;module&gt;
    from ChatGPTScraper import ChatGpt
E   ModuleNotFoundError: No module named 'ChatGPTScraper'</error></testcase><testcase classname="" name="calculation_test" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\kskos\PycharmProjects\pythonSeleniumChatGPT\unitTests\calculation_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
calculation_test.py:2: in &lt;module&gt;
    from ChatGPTScraper import ChatGpt
E   ModuleNotFoundError: No module named 'ChatGPTScraper'</error></testcase><testcase classname="" name="gptPlus_test" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\kskos\PycharmProjects\pythonSeleniumChatGPT\unitTests\gptPlus_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
gptPlus_test.py:1: in &lt;module&gt;
    from ChatGPTScraper import ChatGpt
E   ModuleNotFoundError: No module named 'ChatGPTScraper'</error></testcase><testcase classname="" name="invalid_test" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\kskos\PycharmProjects\pythonSeleniumChatGPT\unitTests\invalid_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
invalid_test.py:1: in &lt;module&gt;
    from ChatGPTScraper import ChatGpt
E   ModuleNotFoundError: No module named 'ChatGPTScraper'</error></testcase><testcase classname="" name="login_test" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\kskos\PycharmProjects\pythonSeleniumChatGPT\unitTests\login_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
login_test.py:1: in &lt;module&gt;
    from ChatGPTScraper import ChatGpt
E   ModuleNotFoundError: No module named 'ChatGPTScraper'</error></testcase><testcase classname="" name="longMemory_test" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\kskos\PycharmProjects\pythonSeleniumChatGPT\unitTests\longMemory_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
longMemory_test.py:2: in &lt;module&gt;
    from ChatGPTScraper import ChatGpt
E   ModuleNotFoundError: No module named 'ChatGPTScraper'</error></testcase><testcase classname="" name="translation_test" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\kskos\PycharmProjects\pythonSeleniumChatGPT\unitTests\translation_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
translation_test.py:2: in &lt;module&gt;
    from ChatGPTScraper import ChatGpt
E   ModuleNotFoundError: No module named 'ChatGPTScraper'</error></testcase><testcase classname="" name="unethical_test" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\kskos\PycharmProjects\pythonSeleniumChatGPT\unitTests\unethical_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
unethical_test.py:1: in &lt;module&gt;
    from ChatGPTScraper import ChatGpt
E   ModuleNotFoundError: No module named 'ChatGPTScraper'</error></testcase></testsuite></testsuites>